In [114]:
# ex_1
# 1
lst = [1] * 15
print(lst)   

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [115]:
# 2
import itertools
itertools.repeat(7, 15)
list(itertools.repeat(7, 15))

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

In [116]:
# 3
lst = list(range(100,151))
print(lst)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]


In [117]:
# 4
lst = list(range(0,101))
for num in lst:
    if num % 2 == 0:
        print(num)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [118]:
# 5
lst = list(range(1950,2020))
lst2 = list(filter(lambda x: (x % 13 == 0), lst))
print("years what divisible by 4 are:", lst2)

years what divisible by 4 are: [1950, 1963, 1976, 1989, 2002, 2015]


In [119]:
# ex_2
# 1
import numpy as np
array = np.zeros(15)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
# 2
array = np.ones(15)
array



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [121]:
# 3
import numpy as np
array = np.array([7])
array2 = np.repeat(array, 15)
print(array2)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [122]:
# 4
array = np.arange(100,151)
array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [123]:
# 5
array = np.arange(1900,2022)
array

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [124]:
# 6
array = np.arange(0,100,2)
print(array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [125]:
# 7
array = np.arange(1950,2021)
filtered = array[array % 4 == 0]
filtered

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

work with NumPy little bit easier

In [126]:
%reload_ext numpy_html

In [127]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

In [128]:
# ex_3
# 1
data = np.arange(1, 50).reshape(7, 7)
data

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [129]:
# 1 extra
A = [[1, 2, 3, 4, 5, 6, 7], 
    [8, 9, 10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19, 20, 21],
    [22, 23, 24, 25, 26, 27, 28],
    [29, 30, 31, 32, 33, 34, 35],
    [36, 37, 38, 39, 40, 41, 42],
    [43, 44, 45, 46, 47, 48, 49]]
A

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

In [130]:
# 2
import numpy as np
np.random.randint(0, 6, (8, 8))

array([[4, 2, 3, 4, 2, 3, 1, 0],
       [1, 0, 1, 4, 0, 2, 4, 3],
       [3, 5, 5, 0, 1, 1, 1, 1],
       [5, 3, 3, 4, 4, 4, 2, 2],
       [4, 2, 1, 0, 2, 5, 4, 2],
       [2, 3, 3, 1, 5, 5, 3, 4],
       [5, 4, 0, 1, 4, 4, 5, 0],
       [5, 3, 1, 3, 1, 2, 0, 5]])

In [131]:
# 3
np.random.randint(-3, 4, (8, 8))

array([[-1, -2,  0,  3,  3,  3, -1, -3],
       [-3,  2,  0,  2,  3, -1,  3, -2],
       [ 3, -3, -3, -1, -3, -2,  0,  0],
       [-2,  3, -2, -1, -1,  2,  2, -2],
       [ 3,  3, -1, -1,  3, -3,  3, -1],
       [-2,  2,  0,  0, -3,  1, -3,  3],
       [ 0,  1,  3, -1,  3,  1,  3,  1],
       [ 1,  2, -2,  3,  2,  0,  2, -2]])

In [132]:
# ex_4
# 1
import random
randomlist = []
for i in range(0,10):
    n = random.randint(0,1)
    randomlist.append(n)
print(randomlist)

[1, 1, 0, 1, 0, 0, 0, 1, 0, 1]


In [133]:
#2
import numpy as np
np.random.randint(0, 6, (8, 8))

array([[5, 3, 1, 5, 4, 0, 2, 1],
       [5, 4, 1, 2, 5, 5, 3, 0],
       [5, 2, 2, 5, 2, 0, 5, 4],
       [1, 5, 2, 2, 0, 2, 1, 2],
       [4, 4, 4, 4, 3, 2, 1, 3],
       [4, 4, 3, 5, 3, 4, 2, 5],
       [2, 3, 0, 5, 1, 5, 0, 5],
       [5, 0, 5, 1, 1, 0, 2, 2]])

In [134]:
# 2 extra
from random import randint
A = [[randint(0, 5) for y in range(10)] for x in range(10)]
print(A)

[[1, 5, 3, 4, 1, 4, 0, 5, 0, 5], [3, 2, 0, 2, 4, 3, 2, 0, 4, 4], [2, 2, 5, 0, 1, 2, 2, 3, 2, 1], [1, 0, 3, 4, 5, 3, 3, 4, 5, 3], [3, 0, 0, 4, 3, 2, 4, 1, 1, 0], [3, 1, 5, 1, 2, 4, 2, 3, 3, 5], [0, 0, 0, 4, 4, 0, 3, 2, 2, 2], [3, 3, 0, 0, 2, 0, 2, 5, 4, 4], [0, 2, 3, 1, 1, 1, 4, 5, 3, 5], [0, 3, 1, 5, 0, 2, 3, 5, 5, 2]]


In [135]:
# ex_5
# 1
import numpy as np
np.random.randint(0, 98, (3, 5))



array([[14, 46,  0, 91, 14],
       [56, 15, 86, 46, 19],
       [14, 41, 93, 96, 63]])

In [136]:
# 2
data = np.arange(128, 256).reshape(8, 16)
data

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

In [137]:
%reload_ext numpy_html

In [138]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

In [139]:
# 3
import numpy as np
np.linspace(0.05, 5, 100).reshape(10, 10)

     

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

In [140]:
# ex_6
# 1
data = np.arange(1, 37).reshape(6, 6)
data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [190]:
slice = data[3:]
slice

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [191]:
slice = data[:3]
slice

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])